### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by NikKovIos** [nerzh/swift-telegram-sdk#36]
```
2381.4 /build/.build/checkouts/swift-telegram-sdk/Sources/SwiftTelegramSdk/Bot/Extensions/HTTPMediaType.swift:193:62: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
2381.4 let fileExtensionMediaTypeMapping: [String: HTTPMediaType] = [
2381.4                                                              ^
2382.1 error: fatalError
```

Reproducing:

1) import SwiftTelegramSdk
2) `docker-compose build`
[docker files.zip](https://github.com/user-attachments/files/17129390/docker.files.zip)

**Comment by nerzh** [comment]
your error says what went wrong. What computer are you compiling this on? How many cores and RAM? What version of the Swift compiler? Simply, if you think logically, your project is compiling everywhere except this docker, then the problem is clearly not in the library. I have compiled in docker more than once, everything still works, but docker is not the topic of this library

**Comment by NikKovIos** [comment]
Oh, I forgot to say

`swift build`, `swift run` works correctly
